### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sooqini** [logicalgrape/paypal-ipn-laravel#1]
I see this a new project and it looks promising, would it be possible to add some usage documentation?

Importing the service provider is obviously straightforward but what about setting up the route for the ipn listener and getting notified of a received ipn?

**Comment by croemmich** [comment]
Hi @sooqini. I added some basic documentation to get you started. Unfortunately I'm a single developer team so I don't have much time for writing documentation, but feel free to send a pull request with documentation changes or additions as you see the need. Thanks!
