### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by jnewing** [logicalgrape/paypal-ipn-laravel#3]
Every time i try to install this using composer i get this.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.1.9
    - Conclusion: don't install laravel/framework v4.1.9
    - Conclusion: don't install laravel/framework v4.1.8
    - Conclusion: don't install laravel/framework v4.1.7
    - Conclusion: don't install laravel/framework v4.1.6
    - Conclusion: don't install laravel/framework v4.1.5
    - Conclusion: don't install laravel/framework v4.1.4
    - Conclusion: don't install laravel/framework v4.1.3
    - Installation request for logicalgrape/paypal-ipn-laravel dev-master -> satisfiable by logicalgrape/paypal-ipn-laravel[d
ev-master].
    - Conclusion: don't install laravel/framework v4.1.2
    - Conclusion: don't install laravel/framework v4.1.1
    - logicalgrape/paypal-ipn-laravel dev-master requires illuminate/support 4.0.\* -> satisfiable by laravel/framework[v4.0.0
, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9], illuminate/support[v4.0.0, v4.0.1, v4.0.1
0, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.0].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.1].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.10].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.2].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.3].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.4].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.5].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.6].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.7].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.8].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.1|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.10|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.2|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.3|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.4|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.5|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.6|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.7|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.8|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.9|don't install laravel/framework v4.1.0
    - Installation request for laravel/framework 4.1.\* -> satisfiable by laravel/framework[v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4
.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9].

**Comment by thatleeguy** [comment]
It's just an issue with it requiring illuminate 4.0.\* and illuminate is currently 4.1.*

Nothing seems breaking in regards to this, at my cursory glance, so it should be a simple requirement change.

**Comment by croemmich** [comment]
Duplicates #6.
