### ISSUE TITLE
Not working with Laravel 4.1.x

### ISSUE THREAD

**Issue by greatwitenorth** [logicalgrape/paypal-ipn-laravel#6]
I believe the following requirement is causing issues in Laravel 4.1.x:

"illuminate/support": "4.0.*"

Should it be changed to ~4.0

I have not tested it though with the latest version of laravel.

**Comment by devlsh** [comment]
Yes this is a problem, is there any way around it without having to fork the repo and put it on packagist?

**Comment by croemmich** [comment]
Sorry for the delay, looking at it soon!
