### ISSUE TITLE
migration:rollback & migration:refresh error

### ISSUE THREAD

**Issue by tkchuah** [logicalgrape/paypal-ipn-laravel#8]
Encounter PHP fatal error when I tried to perform a refresh/rollback after installing this package

PHP Fatal error:  Call to undefined method Illuminate\Database\Schema\MySqlBuilder::dropTable() 

I did some digging and found that dropTable is used for function down() in both CreateIpnOrderItemOptions  & CreateIpnOrderItems class.

Change dropTable to drop seems to have the problem fixed.

thanks
TK Chuah

**Comment by croemmich** [comment]
Fixed by #11.
